import numpy as np

def white_noise(t):
    """
    White noise generated by sampling at random from a uniform distribution.
    """
    N = len(t)
    x = np.random.uniform(-1.0, 1.0, N)
    return x


def brownian_noise(t):
    """
    Brown noise generated
    """
    N = len(t);
    dx = np.zeros(N);
    for n in range(0, N):
        dx[n] = np.random.normal(0, scale=np.sqrt(t[n]))
    x = np.zeros(N);
    for n in range(1, len(x)):
        x[n] = x[n-1] + dx[n]
    return x

# TODO GENERATE PINK NOISE